### ISSUE TITLE
Mouse stuttering with Linux 6.1 due to PSR on GNOME

### ISSUE THREAD

**Issue by stuarthayhurst** [tomsom/yoga-linux#11]
After updating to linux 6.1-rc3, the mouse began stuttering on the desktop, except when the screen was forced to refresh. For some reason, panel self-refresh (PSR) is causing this, but not either earlier kernels.
Regardless of the root cause, using `amdgpu.dcdebugmask=0x10` disabled PSR in the amdgpu driver, and the mouse works again properly ([source code reference](https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/amd/include/amd_shared.h#L250)).

Documenting in case anyone else has the same issue, feel free to close this :)

**Comment by stuarthayhurst** [comment]
Can probably be closed if #12 is merged

**Comment by Myaats** [comment]
Might be worth creating an issue on the kernel bugzilla if it has not already been reported, otherwise this may end up in the 6.1 release.

**Comment by stuarthayhurst** [comment]
I plan to as soon as I have the time spare, I'll get to it later today hopefully

**Comment by stuarthayhurst** [comment]
Seems like this has been fixed by linux 6.1-rc5, as I can't reproduce this anymore.
