### ISSUE TITLE
Tablet Mode irreversible (no keyboard/touchpad input)

### ISSUE THREAD

**Issue by LoredCast** [tomsom/yoga-linux#14]
When put into tablet mode (screen flipped fully back) the keyboard and touchpad seem to get hardware disabled and do not reactivate until rebooted. 
Sometimes it's enough to hibernate/sleep, which in my case then always breaks the touch input and strangely every function key as well. Fixable?

 Tested on Arch with Wayland/Sway and X/i3.

**Comment by Myaats** [comment]
For me enabling iio-sensor-proxy and applying [this patch](https://lore.kernel.org/all/20221004214332.35934-1-soyer@irl.hu/) solved it for my install.

**Comment by tomsom** [comment]
Mmh, if i flip back to "laptop mode" it has always been reactivated(using fedora). Have you already tried the packages listed here https://wiki.archlinux.org/title/Tablet_PC#Tablet_mode ?

**Comment by LoredCast** [comment]
Should have read the wiki better..., thank you!
