### ISSUE TITLE
Three finger swipe?

### ISSUE THREAD

**Issue by imsofi** [tomsom/yoga-linux#22]
Under Fedora 37, using Wayland and GNOME, if i try to active the three finger swipe up, GNOME does not seem to recognize that i did that action.

Curious if anyone else is experiencing this? It might be a possible driver issue with the touchpad but i would like to hear other's experiences.

**Comment by Okazakee** [comment]
I just tested that, wayland with mesa-freeworld and all is ok, i have few updates to kernel to do so wait my edit to confirm :)

**Comment by imsofi** [comment]
Awesome! Then i need to figure out what settings i have touched :sweat_smile:

**Comment by imsofi** [comment]
Yeah so i ended up forgetting that I toggled on xorg a while back for testing purposes.

It was indeed on me 😅
