### ISSUE TITLE
Enable battery threshold for charging

### ISSUE THREAD

**Issue by Okazakee** [tomsom/yoga-linux#23]
I noticed there's no way for us to enable this feature in human ways, but I remember when just installed fedora, that for few reboots the threshold was working, and at 79/80% the battery page was saying "not in charge" or something like that, is there a way to get this working? systemd? config files? tlp?

**Comment by Myaats** [comment]
write `1` to `/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode`

**Comment by Okazakee** [comment]
> write `1` to `/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode`

So a gnome ext i saw yesterday might work, let me find it again: 
![Schermata del 2023-02-01 17-36-32](https://user-images.githubusercontent.com/17621558/216105474-dbc9c74e-eab0-4bee-ab77-e8b0081ef4aa.png)

**Comment by lamarios** [comment]
that extension didn't work for me somehow but  [IdeaPad Controls](https://extensions.gnome.org/extension/5260/ideapad-controls/) did

**Comment by Okazakee** [comment]
> that extension didn't work for me somehow but  [IdeaPad Controls](https://extensions.gnome.org/extension/5260/ideapad-controls/) did

That's a bit "wtf moment", nice you found an alternative
