### ISSUE TITLE
Speaker fix (new?)

### ISSUE THREAD

**Issue by InevitableVegetable** [tomsom/yoga-linux#24]
Hi there, while googling I found this current thread: https://forums.linuxmint.com/viewtopic.php?p=2287773&sid=33a6bc59f9e1ecdb46a923a964fcb2fe#p2287773

Specifically:

>  OK. I just poked around on-line and tried a few things. This is what fixed my sound:
> 
> I upgraded my kernel to 6.1. edited /etc/modprobe.d/alsa-base.conf, and added the following line at the bottom:
> 
> options snd-sof-intel-hda-common hda_model=alc287-yoga9-bass-spk-pin
> 
> That fixed the sound issue. I tried the same string with "yoga7" in place of "yoga9" - since I have a yoga7 - but that did not work.
> 
> Sound is fixed. Finally. Just upgrading the kernel was not enough - I also had to update the alsa-base.conf file.

I haven't tried this myself, but sounds more straight forward than the other fix.

**Comment by imsofi** [comment]
It is not new, its essentially applying the audio patches from https://github.com/PJungkamp/yoga9-linux/

It might work, but there is no reassurance that its safe to run long term, as the audio chips may have been wired up differently between the Yoga models.

Sadly its been quite complicated to get the hda verbs off the Yoga 7, as the resources available for how to do so expect a much older kernel than the minimum version needed to support the Ryzen CPU in the model.

Also see #3
