### ISSUE TITLE
Odd Energy Consumption Reading

### ISSUE THREAD

**Issue by SurnameLiu** [tomsom/yoga-linux#32]
cat /sys/class/power_supply/BAT0/power_now seems to not read the power consumption correctly unless i plug and unplug the charger

can anyone reproduce this?

**Comment by stuarthayhurst** [comment]
It sometimes gets stuck at an old value or at 0 for me, normally after it wakes up from sleep if it does it

**Comment by SurnameLiu** [comment]
seems to be fixed with latest kernel
