### ISSUE TITLE
Fan controls

### ISSUE THREAD

**Issue by Akinzekeel** [tomsom/yoga-linux#40]
It seems that the fans are running much too slowly to keep the system cool for me. This causes a sudden power off shortly after starting up a game, for instance.

**Solutions I've tried**
- fancontrol-gui: did not display anything (mostly empty window)
- thinkfan: cannot set fan speeds (probably just not compatible with this laptop)
- sensors-detect: could not find any sensor
- Changing the performance mode in the UEFI settings: this does influence the fan speed overall but does not seem to react any better to changes in system load / temperature

Is anyone else here affected by this problem?

**Comment by stuarthayhurst** [comment]
Same behaviour, except my system doesn't crash. If it's crashing, you should probably report that to Lenovo as it might be hardware / firmware related.

**Comment by Akinzekeel** [comment]
**Update:** I took @stuarthayhurst's advice and reached out to Lenovo about this problem (especially because I've already had sudden shutdowns before switching this laptop to Linux). They repaired something related to the cooling system and while I need to do more testing, it seems like the problem has been fixed or at the very least been improved.

Since nobody else seems to have had such problems either, I am closing this issue.

**Comment by lamarios** [comment]
My machine recently started facing hard reboots most likely because of temps, @Akinzekeel  when you said they repaired something, did you send your machine back for repairs, or is it a firmware update or something ?

**Comment by Akinzekeel** [comment]
> My machine recently started facing hard reboots most likely because of temps, @Akinzekeel  when you said they repaired something, did you send your machine back for repairs, or is it a firmware update or something ? 

I had to send the laptop to Lenovo for repairs and based on their report they actually swapped out some piece of hardware.
