### ISSUE TITLE
Autorotation: iio-sensor-proxy does not detect any sensors

### ISSUE THREAD

**Issue by ManyNo** [tomsom/yoga-linux#43]
Is iio-sensor-proxy working out of the box for everyone? It doesn't detect any sensors on my machine.
Autorotation works fine in Windows, so it's not a hardware issue.

```
[root@yoga7 ~]# uname -a
Linux yoga7 6.4.1-arch2-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Jul 2023 08:39:40 +0000 x86_64 GNU/Linux
[root@yoga7 ~]# dmidecode -s system-version
Yoga 7 14ARB7
[root@yoga7 ~]# /usr/lib/iio-sensor-proxy -v -r
** (iio-sensor-proxy:12164): DEBUG: 14:58:16.010: Starting iio-sensor-proxy version 3.4
(iio-sensor-proxy:12164): GLib-GIO-DEBUG: 14:58:16.011: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
** (iio-sensor-proxy:12164): DEBUG: 14:58:16.023: No sensors or missing kernel drivers for the sensors
```

**Comment by stuarthayhurst** [comment]
Works fine for me, are you missing the driver for it / have it disabled in your kernel config?

**Comment by ManyNo** [comment]
I'm using the default Arch Linux kernel. Are there any additional drivers/firmwares I need to install?

**Comment by stuarthayhurst** [comment]
What's the output of `lsmod |grep hid_sensor_hub`? That's the driver responsible for the sensor on my system (Debian Sid + kernel 6.4.1)

**Comment by ManyNo** [comment]
The module was indeed blacklisted in /etc/modprobe.d/blacklist.conf :sweat_smile:
Thanks for your help, it is working now.
