### ISSUE TITLE
Mesa drivers for arch

### ISSUE THREAD

**Issue by rodude123** [tomsom/yoga-linux#46]
I've seen that the wiki has info on how to swap to the Freeworld drivers, but what's the status for Arch? I use the Mesa drivers that come with Arch. Can someone who uses an arch/arch-based distro please guide me? Also, I'm happy to give my wiki suggestions for arch users and the commands for those as well

**Comment by 0x9fff00** [comment]
Arch’s official `libva-mesa-driver` package already includes the patented codecs so you don’t need to switch drivers: https://gitlab.archlinux.org/archlinux/packaging/packages/mesa/-/blob/bbf19416001fe68854126a95554f6862a9f510da/PKGBUILD#L130

If hardware acceleration doesn’t work, make sure you’ve completed all the steps at https://wiki.archlinux.org/title/Hardware_video_acceleration

**Comment by rodude123** [comment]
ok cool, thanks
