### ISSUE TITLE
Internal keyboard not working with newer Kernels

### ISSUE THREAD

**Issue by Akinzekeel** [tomsom/yoga-linux#47]
So I recently decided to test the new kernel 6.4 which is now no longer listed as RC / experimental. I was hoping for some AMD CPU enhancements among other things.

Unfortunately my excitement was quickly hampered when I found that after rebooting into the new kernel, the keyboard did not work at all and I was unable to even log in. I could still use the touchpad as well as external USB keyboards, but the internal keyboard didn't do anything. After reverting back to 6.3, I then tried 6.5-rc1 and I had the same problem.

I could not find much information on this so it does not seem to be a widespread issue. Any ideas how I could troubleshoot this? Or does someone else have this problem?

(tested on Manjaro Gnome & KDE versions)

**Comment by Myaats** [comment]
Works fine for me on 6.4.4 (NixOS), likely distro or setup related. I recommend grepping the kernel logs for `i8042` if you decide to attempt to reproduce.

**Comment by 0x9fff00** [comment]
I can reproduce on 6.5-rc3 but not 6.4.6. Likely related to https://github.com/torvalds/linux/commit/a9c4a912b7dc7ff922d4b9261160c001558f9755 which reverted https://github.com/torvalds/linux/commit/9946e39fe8d0a5da9eb947d8e40a7ef204ba016e (the old keyboard fix from 6.0)

**Comment by 0x9fff00** [comment]
See https://lore.kernel.org/all/596b9c4a-fb83-a8ab-3a44-6052d83fa546@augustwikerfors.se/

**Comment by Akinzekeel** [comment]
Thanks for your research. That would explain it.

So I guess the only 2 options from here are
1. Wait for a kernel patch
2. Restore the commit and build the kernel myself

As I have 0 experience with the 2nd option I will probably just wait for some update.

**Comment by 0x9fff00** [comment]
Kernel Bugzilla report: https://bugzilla.kernel.org/show_bug.cgi?id=217718

**Comment by rodude123** [comment]
Can you not just reapply the previous patch and compile the kernel yourself?

**Comment by 0x9fff00** [comment]
This is the patch sent upstream: https://lore.kernel.org/all/20230728191408.18141-1-mario.limonciello@amd.com/

**Comment by zerosign** [comment]
Hi, it's seems 6.4.7 also doesn't work either in `Yoga Slim 7 proX 14ARH7` (or maybe all lenovo notebook zen 3 in that being sell/manufactured on that year). Should I also report this to bugzilla.kernel.org directly ?


```
System Information
        Manufacturer: LENOVO
        Product Name: 82TL
        Version: Yoga Slim 7 proX 14ARH7
```

**Comment by 0x9fff00** [comment]
@zerosign Yes please do so

**Comment by George-Spanos** [comment]
Just updated to 6.4.9 and the keyboard seems to work.

OS: Fedora 38 with KDE
Device: lenovo yoga 7 14arb7
Kernel version: 6.4.9-200.fc38.x86_64

**Comment by 0x9fff00** [comment]
Fedora reverted https://github.com/torvalds/linux/commit/a9c4a912b7dc7ff922d4b9261160c001558f9755 in their downstream kernel. That revert along with patches to avoid regressions for other models will be in 6.5-rc6 and likely in an upstream 6.4 stable release next week. For details see https://lore.kernel.org/all/20230809085526.84913-1-hdegoede@redhat.com/T/ and https://bugzilla.redhat.com/show_bug.cgi?id=2229165

**Comment by stuarthayhurst** [comment]
It seems this has also made it to the mainline kernel now, ready for the next release candidate (rc6?)

**Comment by lamarios** [comment]
Seems like it works for me on fedora with kernel 6.4.9.it was released today.

**Comment by EnderMk9** [comment]
Yup, I can confirm that on 6.4.9 in fedora it's fixed

**Comment by rodude123** [comment]
what about on arch?

**Comment by Akinzekeel** [comment]
I tried 6.4.10.arch1-1 today on Endeavour but the keyboard still didn't work

**Comment by 0x9fff00** [comment]
Looks like 6.4.11 will be released with the fix on Tuesday or Wednesday: https://lore.kernel.org/all/20230813211724.969019629@linuxfoundation.org/

**Comment by zerosign** [comment]
I see the changes are being reverted back based on this patches https://lore.kernel.org/all/20230813211725.649477976@linuxfoundation.org/

**Comment by stuarthayhurst** [comment]
Confirmed working with upstream 6.5-rc6, can this be closed?

**Comment by 0x9fff00** [comment]
Also fixed in 6.4.11

**Comment by Akinzekeel** [comment]
I can't find 6.4.11 on any of my machines and 6.5-rc6 fails to install ("problem importing keys")

**Comment by Akinzekeel** [comment]
After some more troubleshooting, I managed to install kernel 6.5-rc6 and I can confirm that the keyboard works.

Update: I can also confirm that 6.4.11 works
