### ISSUE TITLE
Linux kernel 6.5

### ISSUE THREAD

**Issue by directorscut82** [tomsom/yoga-linux#50]
Hi,
6.5 released 4 days ago. Does anybody noticed any improvements regarding the still unresolved issues?

**Comment by Okazakee** [comment]
Issues about what?

**Comment by directorscut82** [comment]
Microphone recording levels, speakers (bass), 3d performance, sleep/suspend (though I think I don't have any since 6.3)

**Comment by Okazakee** [comment]
> Microphone recording levels, speakers (bass), 3d performance, sleep/suspend (though I think I don't have any since 6.3)

Oh you mean in general, someone has to use a vanilla os to test without applied patches to do that

**Comment by directorscut82** [comment]
Yeap except some commands for the speakers I haven't patched anything and I am almost good to go.

**Comment by stuarthayhurst** [comment]
Linux 6.5 brought a patch for the Samsung PM9B1 SSD in some units, and changed the default for `amd_pstate`, to give better performance, thermals and power draw, especially at idle.

Linux 6.6 should have a patch to enable keyboard backlight control

The sleep / suspend issues are fixed, AFAIK, and the other issues haven't had any updates

**Comment by Okazakee** [comment]
> Linux 6.5 brought a patch for the Samsung PM9B1 SSD in some units, and changed the default for `amd_pstate`, to give better performance, thermals and power draw, especially at idle.

So i can safely remove amd_pstate=guided from my grub line now? What about my issue with resolution selection? I can just select native or 1200p, and cannot find anything on INTERNET related to this type of issue :((

**Comment by directorscut82** [comment]
I am still on acpi haven't tried pstates yet as I use it mostly plugged in

**Comment by stuarthayhurst** [comment]
> So i can safely remove amd_pstate=guided from my grub line now?

Probably, the documentation is a bit murky

> What about my issue with resolution selection? I can just select native or 1200p, and cannot find anything on INTERNET related to this type of issue :((

Report it upstream to a suitable project, if you got it wrong they can probably direct you to the right one, as they will know more about that area

**Comment by stuarthayhurst** [comment]
>What about my issue with resolution selection? I can just select native or 1200p, and cannot find anything on INTERNET related to this type of issue :((

https://gitlab.freedesktop.org/drm/amd/-/issues probably isn't a bad start, if you can't pin it down to another project. Maybe they'll be able to tell what the hardware itself is reporting directly or something.

**Comment by grimthorpe** [comment]
Just to leave my experience - I ran 6.5.0 built from the kernel.org linux-mainline git repository and experienced issues with the display freezing while playing back youtube videos.
This seems to be comparable to the times under 6.4.11 where I would have the display turning off if I didn't have 'amdgpu.dcdebugmask=0x10' on the kernel commandline.

The other thing I noticed is that audio is quieter on 6.5.0 - I do have the systemd script that enables the bottom speakers turned on at boot, so it might be a change to something like that.

I'll give it another go when I've got more time.

**Comment by rinnaz** [comment]
My microphone is not working with both 6.5.0 and 6.5.2 built from the kernel.org

**Comment by 0x9fff00** [comment]
> My microphone is not working with both 6.5.0 and 6.5.2 built from the kernel.org

See #51

**Comment by stuarthayhurst** [comment]
Can this be closed?

**Comment by giorgos-epitropou-obs** [comment]
I guess now that 6.6 is released the question is not relevant anymore

**Comment by giorgos-epitropou-obs** [comment]
forgot to ask @stuarthayhurst do you know if 6.6 fixed the keyboard issues you mentioned?

**Comment by stuarthayhurst** [comment]
Yes, the keyboard backlight is now exposed to userspace, so anything that supports them can read and control it.

https://github.com/torvalds/linux/commit/ecaa1867b5243cf99e6ce9b46e372a66bd7cbfa2
