### ISSUE TITLE
Internal microphone not working since kernel 6.5/6.4.13/6.1.50

### ISSUE THREAD

**Issue by 0x9fff00** [tomsom/yoga-linux#51]
This is caused by https://github.com/torvalds/linux/commit/c008323fe361bd62a43d9fb29737dacd5c067fb7. I'll submit a patch for this soon so I'm opening this issue for tracking.

**Comment by 0x9fff00** [comment]
Patch submitted: https://lore.kernel.org/all/20230911213409.6106-1-git@augustwikerfors.se/

**Comment by sven-frotscher** [comment]
@0x9fff00 I had a similar issue with my Yoga 7 Gen 8 (14ARP8, Product Name 82YM, don't know about its siblings) and can confirm adding it to the quirks list fixes my mic.

Do you want to add an entry to your patch or should I reply with one of my own on the mailing list?

EDIT 2: I see your patch is already applied for v6.6-rc3, I'll send in another one.

**Comment by EnderMk9** [comment]
Do we know in which versions is the patch shipping?

**Comment by sven-frotscher** [comment]
@0x9fff00's patch is in the 6.6-rc3 kernel and may be backported to earlier stable versions since it fixes a regression. I don't know about mine since it hasn't made it to a subsystem maintainer's tree, let alone mainline, yet.

**Comment by 0x9fff00** [comment]
> Do we know in which versions is the patch shipping?

I believe normally it would have been in stable kernels this week but it seems Greg KH has been busy with conferences so there hasn't been a stable release. Most likely 6.5.y and 6.1.y kernels with the patch will be released next week.

**Comment by 0x9fff00** [comment]
Fixed in 6.6-rc3/6.5.6/6.1.56
