### ISSUE TITLE
Regressions Kernel 6.5 (wifi, audio)

### ISSUE THREAD

**Issue by kekkc** [tomsom/yoga-linux#53]
Hi everyone,

bought a new 14ARB7 AMD 6800u and recognized the following regressions:

UPDATE:

Suse Tumbleweed KDE (Kernel 6.6.1) https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-KDE-Live-x86_64-Current.iso :
- wifi doesn't work (trys to connect & then says "wifi network could not be found" and disconnected, no errors / warnings in journalctl, [log.txt](https://github.com/tomsom/yoga-linux/files/13402935/log.txt))
- mic works
- audio (probably bass speakers, sound is quiet)

Kubuntu 23.10 (Kernel 6.5) / Fedora 39 / Ubuntu 23.10:
- wifi doesn't work (trys to connect & then says deactivated, no errors / warnings in journalctl, [log.txt](https://github.com/tomsom/yoga-linux/files/13402935/log.txt))
- mic doesn't work
- audio only tweeters

Kubuntu 23.04 (Kernel 6.2):
- wifi works
- mic works (low volume)
- audio only tweeters

Rest works (in wayland sessions, tablet mode, touch, auto-rotation, cam, s0x standby, fans quiet [via UEFI]) --> tested in Kubuntu, Tumbleweed

Anyone else who got especially wifi working in recent distros?

Greetz

**Comment by RayOfLight1** [comment]
I'm using a different distro (gentoo), I'm using kernel 6.6, but even since
5.0, on the same laptop model and cpu, I have no problems with the wireless.
I was bundled with "MEDIATEK Corp. MT7922 802.11ax PCI Express Wireless
Network Adapter" FYI
The audio bug has been "workaround"ed by creating a systemd service to
reset the i2c device at each resume/restart.
Microphone moves the sound meter in kmix so I think it also works... I
cannot test in audacity as it seems to not support pipewire :(

There seems to be something going on at your end...

Regards,

Missatge de kekkc ***@***.***> del dia dg., 19 de nov. 2023 a
les 11:24:

**Comment by 0x9fff00** [comment]
Mic not working is #51 but it was fixed in 6.5.6 and 6.6, are you sure it doesn’t work in 6.6.1? If so could you provide the output of `grep '' /sys/class/dmi/id/* 2>/dev/null` (as a regular user, not root)?

I have the same Wi-Fi adapter as @RayOfLight1 and haven’t noticed any problems with it either, could you share the output of `lspci -nn` to know if you have the same model?

**Comment by kekkc** [comment]
>Mic not working is #51 but it was fixed in 6.5.6 and 6.6, are you sure it doesn’t work in 6.6.1?

Confirmed, Mic is working in 6.6.1 Tumbleweed, seems I only tested in 6.5 or it was some quirk in Cheese ;)

>I was bundled with "MEDIATEK Corp. MT7922 802.11ax PCI Express Wireless Network Adapter" FYI
> I have the same Wi-Fi adapter as @RayOfLight1 and haven’t noticed any problems with it either, could you share the output of lspci -nn to know if you have the same model?

Seems exactly the same what I have. In parallel I also tested "extreme performance" mode in UEFI, no difference. Was not able to test Gentoo, because it wouldn't let me create a connection in the live session.

Any other idea how I could debug this

`lspci -nn`
>00:00.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Family 17h-19h PCIe Root Complex [1022:14b5] (rev 01)
00:00.2 IOMMU [0806]: Advanced Micro Devices, Inc. [AMD] Family 17h-19h IOMMU [1022:14b6]
00:01.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Family 17h-19h PCIe Dummy Host Bridge [1022:14b7] (rev 01)
00:02.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Family 17h-19h PCIe Dummy Host Bridge [1022:14b7] (rev 01)
00:02.3 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Family 17h-19h PCIe GPP Bridge [1022:14ba]
00:02.4 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Family 17h-19h PCIe GPP Bridge [1022:14ba]
00:02.5 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Family 17h-19h PCIe GPP Bridge [1022:14ba]
00:03.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Family 17h-19h PCIe Dummy Host Bridge [1022:14b7] (rev 01)
00:03.1 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Family 19h USB4/Thunderbolt PCIe tunnel [1022:14cd]
00:04.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Family 17h-19h PCIe Dummy Host Bridge [1022:14b7] (rev 01)
00:08.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Family 17h-19h PCIe Dummy Host Bridge [1022:14b7] (rev 01)
00:08.1 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Family 17h-19h Internal PCIe GPP Bridge [1022:14b9] (rev 10)
00:08.3 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Family 17h-19h Internal PCIe GPP Bridge [1022:14b9] (rev 10)
00:14.0 SMBus [0c05]: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller [1022:790b] (rev 71)
00:14.3 ISA bridge [0601]: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge [1022:790e] (rev 51)
00:18.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Rembrandt Data Fabric: Device 18h; Function 0 [1022:1679]
00:18.1 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Rembrandt Data Fabric: Device 18h; Function 1 [1022:167a]
00:18.2 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Rembrandt Data Fabric: Device 18h; Function 2 [1022:167b]
00:18.3 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Rembrandt Data Fabric: Device 18h; Function 3 [1022:167c]
00:18.4 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Rembrandt Data Fabric: Device 18h; Function 4 [1022:167d]
00:18.5 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Rembrandt Data Fabric: Device 18h; Function 5 [1022:167e]
00:18.6 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Rembrandt Data Fabric: Device 18h; Function 6 [1022:167f]
00:18.7 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Rembrandt Data Fabric: Device 18h; Function 7 [1022:1680]
01:00.0 Network controller [0280]: MEDIATEK Corp. MT7922 802.11ax PCI Express Wireless Network Adapter [14c3:0616]
02:00.0 Non-Volatile memory controller [0108]: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983 [144d:a808]
03:00.0 SD Host controller [0805]: Genesys Logic, Inc GL9750 SD Host Controller [17a0:9750] (rev 01)
33:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c1)
33:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt Radeon High Definition Audio Controller [1002:1640]
33:00.2 Encryption controller [1080]: Advanced Micro Devices, Inc. [AMD] VanGogh PSP/CCP [1022:1649]
33:00.3 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Rembrandt USB4 XHCI controller #3 [1022:161d]
33:00.4 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Rembrandt USB4 XHCI controller #4 [1022:161e]
33:00.5 Multimedia controller [0480]: Advanced Micro Devices, Inc. [AMD] ACP/ACP3X/ACP6x Audio Coprocessor [1022:15e2] (rev 60)
33:00.6 Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller [1022:15e3]
34:00.0 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Rembrandt USB4 XHCI controller #8 [1022:161f]
34:00.3 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Rembrandt USB4 XHCI controller #5 [1022:15d6]
34:00.4 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Rembrandt USB4 XHCI controller #6 [1022:15d7]
34:00.5 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Rembrandt USB4/Thunderbolt NHI controller #1 [1022:162e]

**Comment by kekkc** [comment]
Guess this will be hard to debug if it works for most. Will send this laptop in and try my luck with a Lenovo X1 Yoga ;)

**Comment by stuarthayhurst** [comment]
> Guess this will be hard to debug if it works for most. Will send this laptop in and try my luck with a Lenovo X1 Yoga ;)

My Mediatek MT7922 was the most unreliable piece of rubbish I've ever used, it didn't work correctly in Windows either and caused semi-frequent bluescreens. I ended up swapping the card for an Intel AX210 and it's been great since. Hopefully your X1 Yoga doesn't have the same Mediatek card, good luck :)

**Comment by stuarthayhurst** [comment]
Is there anything left to do here, or can this be closed?

**Comment by kekkc** [comment]
X1 Yoga (Gen6) is great, no issues there
