### ISSUE TITLE
Sometimes laptop cannot wake from sleep

### ISSUE THREAD

**Issue by EnderMk9** [tomsom/yoga-linux#57]
Good evening, I am writing some has also encountered this problem. When my laptop goes to sleep in s2idle, most times pressing the keyboard or the power button wakes it, but sometimes it does not wake up and I have to force a reboot, potentially losing data. It seems very random, and began recently, so I suspect it's caused by a kernel update, I'm using 6.6.14 in Fedora. 

Thanks

**Comment by stuarthayhurst** [comment]
Sounds like https://github.com/tomsom/yoga-linux/issues/56#issuecomment-1921805689, which has been reported here: https://gitlab.freedesktop.org/drm/amd/-/issues/3132

**Comment by EnderMk9** [comment]
It's identical, thanks, I'm closing this issue for it's already being discussed in #56
