### ISSUE TITLE
Color reproduction seems "off" after update 

### ISSUE THREAD

**Issue by mcdax** [tomsom/yoga-linux#62]
Since one of the recent updates (Arch, KDE Plasma 6.1.0, 6.9.5-arch1-1), I'm facing a major issue with my screen's color accuracy. The colors appear oversaturated, and it looks like there's a translucent white layer overlaying the screen. I've tried applying an ICC profile based on a review of the notebook, but it hasn’t helped in removing this "overlay".

The problem persists regardless of the brightness / backlight setting. The Night-life filter is disabled.

Has anyone else noticed a similar issue?

**Comment by alegaab** [comment]
Does this happens even when the device is on charge or only on battery (if u are on charge make sure to disable the battery saver mode)

**Comment by mcdax** [comment]
Wow, I have just plugged it in and it is much better now! Thanks!

But I do not find any config for that in the settings.

**Comment by Zateros** [comment]
You can disable this for battery as well by running `grubby --update-kernel DEFAULT --args "amdgpu.abmlevel=0"` as root. This is caused by some amdgpu lcd power saving feature. In theory this was supposed to be fixed to not to enable it for oled displays. (see: https://gitlab.freedesktop.org/drm/amd/-/issues/3359)

**Comment by RayOfLight1** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/issues/52

happening to me @ 6.9.3

kernel 6.6.0 has not got this regression.

**Comment by mcdax** [comment]
After adding the Kernel parameter, everything is fine again. Thank you very much!

**Comment by soyersoyer** [comment]
It will be fixed in 6.11
https://gitlab.freedesktop.org/agd5f/linux/-/commit/76cb763e6ea62e838ccc8f7a1ea4246d690fccc9
