### ISSUE TITLE
"lenovo-ymc: Unknown key 0 pressed" during boot

### ISSUE THREAD

**Issue by stuarthayhurst** [tomsom/yoga-linux#63]
While booting, I get `lenovo-ymc 06129D99-6083-4164-81AD-F092F9D773A6: Unknown key 0 pressed`. The `lenovo-ymc` driver works perfectly fine otherwise, and I only get this warning during boot and not during resume after suspend.

@soyersoyer I noticed you were involved with the driver when I went poking at its source, any idea?

**Comment by soyersoyer** [comment]
This is probably what the device reports at startup. I'll create a patch to ignore that.

**Comment by soyersoyer** [comment]
Unfortunately, this driver does not work reliably for me with the latest BIOS. After 4-5 switches, or if things happen quickly, it gets stuck.
Are you experiencing similar things?

**Comment by stuarthayhurst** [comment]
I can't reproduce that on mine, running BIOS `K5CN44WW`.

I did have an issue a while ago where returning to regular laptop mode would leave the screen upside-down, but I think that was a bug in mutter where it ignored the orientation sensor after it went from tent to laptop mode, missing the correct orientation.

**Comment by Myaats** [comment]
> Unfortunately, this driver does not work reliably for me with the latest BIOS. After 4-5 switches, or if things happen quickly, it gets stuck. Are you experiencing similar things?

I have experienced this on KDE Plasma 6, sometimes it seems to fix itself after a while.

**Comment by soyersoyer** [comment]
Unfortunately the lenovo_ymc_trigger_ec sometimes produces a "Thermal Management button" ACPI event. So sometimes it also changes the platform profile in [v6.10](https://github.com/torvalds/linux/commit/822188bf55e1ae6f5c41272382b2aa5f206bc6ab). This quirk needs to be improved.

And there is a race, the return values ​​of ACPI calls get mixed up. I'll cook a patch.

**Comment by soyersoyer** [comment]
The patches are in the [master](https://github.com/torvalds/linux/commit/d74da846046aeec9333e802f5918bd3261fb5509). 6.11 also [fixes](https://github.com/torvalds/linux/commit/76cb763e6ea62e838ccc8f7a1ea4246d690fccc9) the ABM OLED bug.

**Comment by stuarthayhurst** [comment]
> The patches are in the [master](https://github.com/torvalds/linux/commit/d74da846046aeec9333e802f5918bd3261fb5509). 6.11 also [fixes](https://github.com/torvalds/linux/commit/76cb763e6ea62e838ccc8f7a1ea4246d690fccc9) the ABM OLED bug.

Thanks, does this also sort the "lenovo-ymc: Unknown key 0 pressed" message?

**Comment by stuarthayhurst** [comment]
https://lore.kernel.org/all/371e1476-1b7c-4993-b481-132b7552b572@redhat.com/

Patch picked up upstream, thanks
