### ISSUE TITLE
Samsung SSD removed when resuming from s2idle

### ISSUE THREAD

**Issue by 0x9fff00** [tomsom/yoga-linux#9]
Documenting this in case anyone else has this issue:

The Samsung PM9B1 512G SSD found in some units reports eui as `0001000200030004` when resuming from s2idle, causing the device to be removed with this error in dmesg:

```
nvme nvme0: identifiers changed for nsid 1
```

I’ve submitted an initial patch for this here: https://lore.kernel.org/all/20221116171727.4083-1-git@augustwikerfors.se/T/

Kernel Bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=217649

Edit: ~~see https://lore.kernel.org/all/20230731185103.18436-1-mario.limonciello@amd.com/ for a more general patch~~ rejected due to concerns about data corruption for other devices, use the quirk patch instead

**Comment by Okazakee** [comment]
Any news on the fw update?

**Comment by 0x9fff00** [comment]
> Any news on the fw update?

Kanchan Joshi at Samsung responded here: https://lore.kernel.org/all/20221206055928.GB24451@test-zns/

> Took more time than I wanted. Firmware team mentioned that issue existed
> in this firmware. This is fixed in new firmware, but bit of travel time
> is involved when official release from OEM (Lenovo) comes out.
> 
> Hope the information is sufficient, and quirk can go in.
> 
> If required, 
> Acked-by: Kanchan Joshi \<joshi.k@samsung.com\>

**Comment by Okazakee** [comment]
Good news, I'm waiting this to finally switch to fedora, I do not remember if I can update the firmware later from gnome/some 3rd party app or do I just have to wait from windows update?

**Comment by stuarthayhurst** [comment]
I contacted Lenovo, they said their technical team is aware of the firmware and working on an update. Not sure if that'll be available through `fwupd`, or if it'll only be available through their Windows tools, but I'll update this when I get the update.

**Comment by Okazakee** [comment]
I finally switched totally to fedora, the fact that after all this time it is still broken kills my whole experience... Hope to see news asap.

**Comment by stuarthayhurst** [comment]
Been checking daily, no update yet.
If they release something, it'll be on one of these 3 links:
[LFVS PM9B1 firmware updates](https://fwupd.org/lvfs/search?value=pm9b1)
[Lenovo Yoga 7 Gen 7 Drivers & Downloads](https://pcsupport.lenovo.com/gb/en/products/laptops-and-netbooks/yoga-series/yoga-7-14arb7/downloads/driver-list)
[Lenovo Support](https://pcsupport.lenovo.com/gb/en/products/laptops-and-netbooks/yoga-series/yoga-7-14arb7/documentation/doc_kb)

Previously, they've released an update to their NVMe firmware update tool, and added it to the drivers and download page for the affected device. Since this laptop isn't officially Linux supported, that's most likely, but we may see an update on the LVFS if they have any affected thinkpads.

**Comment by Okazakee** [comment]
> 

I mean, i could just run an sd with windows just to update if it get released in WU, it is just a shame to see how much stuff like this gets scheduled on lowest priority, even for capitalistic companies...

**Comment by stuarthayhurst** [comment]
I went for something similar, I've kept mine as a dual boot with the minimum size for Windows to still be able to install updates. I'd rather run 100% Linux, but Windows is still needed for BIOS and firmware updates sadly.

**Comment by Okazakee** [comment]
I builded 6.1.7 kernel and booted in debug mode, it was working just the same as before the kernel switch, i followed this guide, the only thing i didn't follow up was the fact i put the patch with .txt extention instead of .patch

**Comment by stuarthayhurst** [comment]
What did you use to apply the patch to the kernel source?

**Comment by Okazakee** [comment]
> What did you use to apply the patch to the kernel source?

I'm building it again with .patch, i was very tired at the time, it was just explained to be ".patch"

**Comment by Okazakee** [comment]
It builded, nothing changed at all

**Comment by stuarthayhurst** [comment]
Strange, if you're definitely applying the patch to a fresh build of the kernel, definitely booting the custom kernel and definitely have a Samsung PM9B1 SSD, I can't see why it wouldn't work

**Comment by Okazakee** [comment]
> Strange, if you're definitely applying the patch to a fresh build of the kernel, definitely booting the custom kernel and definitely have a Samsung PM9B1 SSD, I can't see why it wouldn't work

edit: I just checked, it seems like my samsung ssd is another one:
model SAMSUNG MZAL4512HBLU-00BL2 (7L1QHXC7)
serial n S67MNF1T654690

**Comment by stuarthayhurst** [comment]
Yep that's the correct SSD, its product name is PM9B1, but there's very little from Samsung published on it

**Comment by Okazakee** [comment]
> Yep that's the correct SSD, its product name is PM9B1, but there's very little from Samsung published on it

Even trying to install the .cab from dell says no supported device

**Comment by stuarthayhurst** [comment]
Same for my SSD, it's got Dell's vendor ID on that firmware file or something along those lines, so the 2 SSDs don't appear the same to LVFS. Since it's an OEM SSD, we need Lenovo to publish the firmware themselves sadly

**Comment by Okazakee** [comment]
> Same for my SSD, it's got Dell's vendor ID on that firmware file or something along those lines, so the 2 SSDs don't appear the same to LVFS. Since it's an OEM SSD, we need Lenovo to publish the firmware themselves sadly

O swear if not for the warranty I would already have swapped that with another ssd

**Comment by Okazakee** [comment]
New bios update, no ssd fw upgrade 💀

**Comment by stuarthayhurst** [comment]
I asked for an update from tech support, as they still hadn't publish the release after months. They said this:
>Thank you for contacting Lenovo technical support. 
>
>Please note that once the update is released, it will be available on our Lenovo Support site. Thank you for your patience in the meantime. 
>
>For any further questions, do not hesitate to contact us.

So no update on a time scale, but at least we know where it'll be uploaded :shrug:

**Comment by Okazakee** [comment]
> I asked for an update from tech support, as they still hadn't publish the release after months. They said this:
> >Thank you for contacting Lenovo technical support. 
> >
> >Please note that once the update is released, it will be available on our Lenovo Support site. Thank you for your patience in the meantime. 
> >
> >For any further questions, do not hesitate to contact us.
> 
> So no update on a time scale, but at least we know where it'll be uploaded :shrug: 
> 

I honestly think they won't, there is not a single update inherent to ssd,  "memory" or "storage". It is more plausible it comes through ms updates, or embedded in bios update or something like that

**Comment by Okazakee** [comment]
> There's probably nothing related to storage, as they haven't uploaded any drivers related to it yet, and it'll appear when they push a driver / update in that category. I can't say I'm impressed with the service, I'm not sure when to cut my losses and just replace the SSD and suck up any warranty problems.

I hope to resist till this summer, I am just greatful the laptop battery is just awsome with amd p state implementation.

**Comment by stuarthayhurst** [comment]
> I'm stuck on this one - the FW team reached out to Samsung to see if there were fixes that we should be picking up and Samsung reported back that there are no Linux issues reported against this part :(

> I'll try reaching out to the Samsung person on the upstream mailing list...because this is going nowhere fast right now.

Taken from https://github.com/fwupd/firmware-lenovo/issues/308, hopefully this leads somewhere

**Comment by stuarthayhurst** [comment]
>  1) Fix issue that display SSD number.
>  2) Fix issue that the ssd will lost after doing crisis.

New BIOS, found this in the changelog.. I'm busy right now, but I'll trial this later, hopefully that's what we needed.

**Comment by Okazakee** [comment]
> > 1. Fix issue that display SSD number.
> > 2. Fix issue that the ssd will lost after doing crisis.
> 
> New BIOS, found this in the changelog.. I'm busy right now, but I'll trial this later, hopefully that's what we needed.

installing it now

**Comment by SeekingGoodTech** [comment]
I was able to get suspend/resume working with the patch that [0x9fff00](https://github.com/0x9fff00) provided. I wonder if the Linux kernel policy to not include this quirk is appropriate given there has been no firmware update issued.

**Comment by SeekingGoodTech** [comment]
> are you on fedora? if so, can you tell me how to correctly patch my kernel?

I am on Ubuntu. I followed the instructions to build a kernel from here:
https://davidaugustat.com/linux/how-to-compile-linux-kernel-on-ubuntu
I imagine there would be similar instructions somewhere for fedora.

In my case, I downloaded the source for 6.2.11 from kernel.org. I applied the patch directly to the downloaded kernel source.
Before making the kernel, I edited the following file:
linux-6.2.11/drivers/nvme/host/pci.c
I used gEdit but you can use whatever editor you're comfortable with.
To add the quirk, change line 3450 & 3451 to read:
`
	{ PCI_DEVICE(0x144d, 0xa80b),   /* Samsung PM9B1 256G and 512G */
		.driver_data = NVME_QUIRK_DISABLE_WRITE_ZEROES | NVME_QUIRK_BOGUS_NID, },
`

then made the kernel per the instructions in the above link. After installing the kernel and rebooting, I now have suspend and resume working.

**Comment by shiftyphil** [comment]
Some progress according to MarkRHPearson on Lenovo forums.

 https://forums.lenovo.com/t5/Other-Linux-Discussions/Firmware-Update-for-Samsung-SSD-PM9B1-in-Yoga-7-Gen-7-14ARB7/m-p/5196929?page=2#5984302

> It will take time to get this implemented, qualified and rolled out so guidance is expect to see the FW updates show up in July.


Not sure why this didn't get communicated from Samsung to Lenovo back in December, but at least we're getting there now.

**Comment by Okazakee** [comment]
> Some progress according to MarkRHPearson on Lenovo forums.
> 
> https://forums.lenovo.com/t5/Other-Linux-Discussions/Firmware-Update-for-Samsung-SSD-PM9B1-in-Yoga-7-Gen-7-14ARB7/m-p/5196929?page=2#5984302
> 
> > It will take time to get this implemented, qualified and rolled out so guidance is expect to see the FW updates show up in July.
> 
> Not sure why this didn't get communicated from Samsung to Lenovo back in December, but at least we're getting there now.

I cannot believe my eyes, not only a confirm of the issue, but an ETA. I'm going to cry now, thx for the news

**Comment by Okazakee** [comment]
Any news on implementation? I am just waiting for new bios hoping for the best

**Comment by stuarthayhurst** [comment]
It's a firmware update for the SSD, which is unlikely to come via BIOS. Lenovo have a firmware update tool [here](https://support.lenovo.com/us/en/downloads/ds119265), which I'd assume is most likely (Windows only). Since the SSD has also shown up in a Linux supported model, it might appear on the LVFS, [here](https://fwupd.org/lvfs/search?value=pm9b1). I've been checking those 2 and the generic support download page for our laptop every few days, I'll update as soon as I've got something.

**Comment by stuarthayhurst** [comment]
Hm, another new firmware for Dell laptops with the PM9B1 SSD, so that's 3 that Dell have released in the time Lenovo have released 0.

**Comment by realquaker** [comment]
I bought new Samsung Evo 1TB. It works fine, no issues. And then sold buggy OEM SSD to Windows user.

**Comment by Okazakee** [comment]
> I bought new Samsung Evo 1TB. It works fine, no issues. And then sold buggy OEM SSD to Windows user.

Do you know if it can fit 80mm ssds?

**Comment by stuarthayhurst** [comment]
From https://psref.lenovo.com/syspool/Sys/PDF/Yoga/Yoga_7_14ARB7/Yoga_7_14ARB7_Spec.pdf, it has a 2280 slot. I took mine apart to test an AX210 card, and can confirm it has one. Since we have PM9B1s, there's a metal insert to make the short SSD fit in a 2280.

**Comment by 0x9fff00** [comment]
This was [brought up on the kernel mailing list again](https://lore.kernel.org/all/d0ce0f3b-9407-9207-73a4-3536f0948653@augustwikerfors.se/) due to a [Bugzilla report](https://bugzilla.kernel.org/show_bug.cgi?id=217649). Also, [someone else submitted the quirk](https://lore.kernel.org/all/b99a5149-c3d6-2a9b-1298-576a1b4b22c1@gmail.com/t/) on 11 June but without mentioning suspend, I've asked if it's the same issue.

**Comment by Okazakee** [comment]
> Documenting this in case anyone else has this issue:
> 
> The Samsung PM9B1 512G SSD found in some units reports eui as `0001000200030004` when resuming from s2idle, causing the device to be removed with this error in dmesg:
> 
> ```
> nvme nvme0: identifiers changed for nsid 1
> ```
> 
> I’ve submitted an initial patch for this here: https://lore.kernel.org/all/20221116171727.4083-1-git@augustwikerfors.se/T/
> 
> Kernel Bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=217649

Do you still have the same error? I need a screenshot of the error to get a free SSD replacement from Lenovo, my problem is that on Tumbleweed the error does not appear, it just stop working or outputs other errors

**Comment by stuarthayhurst** [comment]
If the system doesn't totally die, swap to another TTY and try your luck with `journalctl` or `dmesg`.

**Comment by Okazakee** [comment]
> If the system doesn't totally die, swap to another TTY and try your luck with `journalctl` or `dmesg`.
> 
> EDIT: You might have better luck if you open the TTY first to something like `dmesg -w`, then trigger the crash

It worked with the smesg watch, thank you very much

**Comment by stuarthayhurst** [comment]
> EDIT: I suggest you all to do this, it's a free replacement, an IBM technician will replace the SSD in my house, so i will just clone the current partitions in an img using clonezilla and then restore the img to the new ssd.

I've sent my laptop in for repairs twice already (dead USB board and dodgy trackpad), I really can't be arsed to send it back again. TBH I'll probably just throw a 1 or 2 TB, higher spec SSD in next time I see a good sale.

Just a heads up, this laptop seems very reliant on EFI vars to boot the right OS. After resetting the laptop to send in for repairs and then `dd`ing the original image back on, it fails to boot. Livebooting, mounting the partitions, loading and mounting the efivars, chrooting in and reinstalling GRUB fixes this reliably.

Strange, since USB sticks seem to boot fine. Perhaps it just skips scanning the internal drive for bootable partitions?

**Comment by shiftyphil** [comment]
> Just a heads up, this laptop seems very reliant on EFI vars to boot the right OS.

GRUB seems to not install to the default location (EFI\boot\bootx64.efi) these days.
Might be a distro decision or a GRUB decision, possibly based on whether Windows Boot Manager is there already.

Anything that wipes the EFI variables leads to an annoying recovery process to restore them, or you can copy GRUB (or something like fallback.efi that can automatically set the EFI variables) to the default location.

**Comment by superm1** [comment]
Does this patch help?

[0001-nvme-Don-t-fail-if-NSIDs-change-on-resume.patch](https://github.com/tomsom/yoga-linux/files/12186660/0001-nvme-Don-t-fail-if-NSIDs-change-on-resume.patch)

**Comment by 0x9fff00** [comment]
@superm1 With that patch applied I still get the `identifiers changed for nsid 1` but the SSD now works after resume. Thanks!

**Comment by superm1** [comment]
> @superm1 With that patch applied I still get the `identifiers changed for nsid 1` message but the SSD now works after resume. Thanks!

Yup fully expected. I'll send some variation of this upstream for discussion soon and CC you when I do.

**Comment by superm1** [comment]
OK here's the version I think I can take for discussion.  Should functionally work the same and show the error once after the first suspend/resume cycle.  Can you please test it as well?

[v2.txt](https://github.com/tomsom/yoga-linux/files/12188409/v2.txt)

**Comment by 0x9fff00** [comment]
@superm1 Yes that patch works too. On the first resume I get...
```
nvme nvme0: identifiers changed for nsid 1
nvme nvme0: use of /dev/disk/by-id/ may cause data corruption
```
...and on later resumes I instead get
```
nvme nvme0: Ignoring bogus Namespace Identifiers
```

**Comment by 0x9fff00** [comment]
Update on this: @superm1’s patch was rejected due to [concerns that it could cause data corruption for other devices](https://lore.kernel.org/all/ZMgHE2wu4T4OfrTR@kbusch-mbp/T/#u), however my original quirk patch was applied instead and should be in 6.5:

https://lore.kernel.org/all/ZMlrGNw5OMW3yxId@kbusch-mbp.dhcp.thefacebook.com/
https://git.infradead.org/nvme.git/commit/688b419c57c13637d95d7879e165fff3dec581eb

It would of course still be ideal if Lenovo released the firmware update to fix the root cause, but at least now we’ll get suspend working with the upstream kernel

**Comment by Okazakee** [comment]
> Update on this: @superm1’s patch was rejected due to [concerns that it could cause data corruption for other devices](https://lore.kernel.org/all/ZMgHE2wu4T4OfrTR@kbusch-mbp/T/#u), however my original quirk patch was applied instead and should be in 6.5:
> 
> https://lore.kernel.org/all/ZMlrGNw5OMW3yxId@kbusch-mbp.dhcp.thefacebook.com/ https://git.infradead.org/nvme.git/commit/688b419c57c13637d95d7879e165fff3dec581eb
> 
> It would of course still be ideal if Lenovo released the firmware update to fix the root cause, but at least now we’ll get suspend working with the upstream kernel

now that i changed ssd lmao, thanks a lot for your work anyway!

**Comment by stuarthayhurst** [comment]
New firmware for the PM9B1 posted by Lenovo:
 - https://support.lenovo.com/us/en/downloads/ds119265
 - https://fwupd.org/lvfs/devices/com.lenovo.PM9B1.firmware.v220116

The update via `fwupd` seems to have no interest in my device, I haven't tried the Windows tool yet.

**Comment by stuarthayhurst** [comment]
> Update on this: @superm1’s patch was rejected due to [concerns that it could cause data corruption for other devices](https://lore.kernel.org/all/ZMgHE2wu4T4OfrTR@kbusch-mbp/T/#u), however my original quirk patch was applied instead and should be in 6.5:
> 
> https://lore.kernel.org/all/ZMlrGNw5OMW3yxId@kbusch-mbp.dhcp.thefacebook.com/ https://git.infradead.org/nvme.git/commit/688b419c57c13637d95d7879e165fff3dec581eb
> 
> It would of course still be ideal if Lenovo released the firmware update to fix the root cause, but at least now we’ll get suspend working with the upstream kernel

Seems it's been pulled into mainline Linux now, thanks :D

It would be nice if Lenovo released the firmware update for the Lenovo specific variant, but I guess that's somewhere on the way when they fix whatever issue they found.

Does this mean this issue can finally be closed?

**Comment by EnderMk9** [comment]
Any idea when is it going to reach mainline distros?

**Comment by stuarthayhurst** [comment]
6.5-rc6 will be released tomorrow with this, so 6.5 will probably release in either a week or 2 weeks. After that, it depends on your distro. Arch, Debian Experimental and other rolling release distros should get it within days to weeks, stable distros will take months.

If Lenovo release the firmware update, as soon as you can apply it you won't need the kernel patch.

**Comment by 0x9fff00** [comment]
The patch has also been queued up for the 6.4 and 6.1 stable kernels which should be released next week: https://lore.kernel.org/all/2023081258-marital-idly-e4da@gregkh/

**Comment by EnderMk9** [comment]
Thanks!

**Comment by 0x9fff00** [comment]
Fixed in 6.5-rc6, 6.4.11 and 6.1.46

**Comment by Jalopy-Tech** [comment]
I have model MZAL41T0HBLB-00BL2. I have tried kernels 6.5-rc6 and 6.4.11: suspend and wake up work without a problem.

Notes:
I used the application Mainline Kernels to install the kernels.
I use Open Razer. I had to install gcc-13 to avoid a clash with 6.5-rc6.

**Comment by favelanky** [comment]
I have model SAMSUNG MZVL4512HBLU-00BTW. Was on 4.6.10 (arch linux), after updating to 4.6.11 the problem was gone.

Thanks a lot!
